# Generated by Django 3.1.4 on 2020-12-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojedine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('struja', models.DecimalField(decimal_places=1, max_digits=7)),
                ('plin', models.DecimalField(decimal_places=3, max_digits=7)),
                ('voda', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
