# Generated by Django 3.1.4 on 2020-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojedine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('plin', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Struja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('struja', models.DecimalField(decimal_places=1, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Voda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('voda', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Pojedine',
        ),
    ]
